### PR TITLE
Create ucb-nle.md

### PR DESCRIPTION
**Pull request by arohrbach**

### CODE REVIEW

**Comment by arohrbach** [comment]
Added "Natural language explanations for fine-grained classification" and "Multi-step salience with neural modular networks"

**Comment by arohrbach** [comment]
Added "Explainable AI self-driving controller"

**Comment by arohrbach** [comment]
Added "Datasets with multimodal explanations"; did minor corrections

**Comment by brianhhu** [comment]
I made a few minor changes, mainly fixing up the superscript notation for affiliations. A couple of quick questions:

1) Ronghang's paper link is currently to arXiv- I assume this is is an updated version of the original ECCV '18 paper?

2) The limitations section of the "multimodal explanations datasets" contribution is currently blank- I assume this is intentional?

3) I added the license to Lisa's official repo to the natural language explanations contribution. I understand there are two linked repos, but I think it still makes sense to try and include a license file.

4) For Lisa's paper, would it make sense to link to the [Springer conference proceedings](https://link.springer.com/chapter/10.1007/978-3-319-46493-0_1)? There is a pdf there, and I also noticed a link to supplemental information which is missing from the arXiv version.

5) Finally, I know some of these contributions were also covered in Applied AI Letters submissions (with more of a retrospective flavor). Would it make sense to include those papers as links as well or is there too much overlap?

Thanks for putting these together!

**Comment by arohrbach** [comment]
Hi Brian,

1: Feel free to change that to: https://openaccess.thecvf.com/content_ECCV_2018/papers/Ronghang_Hu_Explainable_Neural_Computation_ECCV_2018_paper.pdf <https://openaccess.thecvf.com/content_ECCV_2018/papers/Ronghang_Hu_Explainable_Neural_Computation_ECCV_2018_paper.pdf>
Should be about the same.

2: I did not think of limitations for a dataset :)

3: Sounds good.

4: Sure, probably even better to use: https://link.springer.com/content/pdf/10.1007%2F978-3-319-46493-0_1.pdf <https://link.springer.com/content/pdf/10.1007/978-3-319-46493-0_1.pdf>

5: Probably too much overlap.

Best,
Anja

**Pull request merged**
